# Generated by Django 2.2.7 on 2019-11-22 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_itempictures'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='itempictures',
            new_name='Profile',
        ),
    ]
