# Generated by Django 2.2.7 on 2019-11-23 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_auto_20191123_0002'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='productdetails',
            field=models.TextField(default='intented to be added'),
            preserve_default=False,
        ),
    ]
